---
# defaults file for get_pkg

deploy_root:

package:
  name:
  alias:
  version:
  dgst_algo:
  checksum:
  # Choices: source, binary
  type:

package_fullname: "{{ package['name'] }}-{{ package['version'] }}"
package_tarball: "{{ package_fullname.capitalize() }}.tar.xz"

package_url:
